
#type: args

train:
  epochs: 20
  batch_size: 8
  lr: 0.0001
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.7
  num_steps: 275
  schedule: "quad"
  is_linear: False
  noise_esti: False
  cfg: True
  c_mask_prob: 0.2
  ddim: True
  sample_steps: 120
  sample_method: "quad"
  pre_norm: False
  # Recommended defaults after experiments
  time_weight: 0.1

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  num_sample_features: 64
  timestep_branch: False
  timestep_emb_cat: True
  with_texts: True
  relative_size_emb_cat: False
  decomp: False
  llm: "bert"
  llm_layers: 0
  rag_topk: 1
  cot_temperature: 0.55
  guide_w_default: 1.2
